### ISSUE TITLE
[BUG] DropBox/dbx Listener Does Not Start

### ISSUE THREAD

**Issue by WhatIsRealityBro** [BC-SECURITY/Empire#326]
## Empire Version
- Empire 3.4.0

## OS Information (Linux flavor, Python version)
- OS: Kali Linux
- Python: 3.8.5

## Describe the bug
Whenever I attempt to start a DropBox/dbx listener it fails to start and shows a python error.

## To Reproduce
1. uselistener dbx
2. set APIToken (My DropBox App APIToken)
3. execute
4. Python Error:
```
Exception in thread Thread-15:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/share/powershell-empire/lib/common/helpers.py", line 1026, in __run
    self.__run_backup()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/share/powershell-empire//lib/listeners/dbx.py", line 874, in start_server
    stagerCodeps = self.generate_stager(listenerOptions=listenerOptions, language='powershell')
  File "/usr/share/powershell-empire//lib/listeners/dbx.py", line 404, in generate_stager
    return RC4IV + encryption.rc4(RC4IV+stagingKey, randomizedStager)
TypeError: can't concat str to bytes
```

## Expected behavior
Start a DropBox/dbx Listener.

## Screenshots
![image](https://user-images.githubusercontent.com/66802253/94647360-e2a91500-02b5-11eb-8717-1a802090ef94.png)

## Additional context
N/A

**Comment by Cx01N** [comment]
@WhatIsRealityBro Thanks for catching this! I opened a PR that should fix the issue. If you have a chance to test it, that would be awesome. I only tested the dropbox legacy API, so I am unsure if it will run with their newer one.

**Comment by WhatIsRealityBro** [comment]
@Cx01N Thanks for the quick reply and fix! So it looks like the listener starts fine now but when I get an agent to check in I get the following error:

```
(Empire: listeners/dbx) > [*] New agent 6GUPWF25 checked in
[*] Uploading key negotiation part 2 to /Empire/staging/6GUPWF25_2.txt for 6GUPWF25
[!] Exception in agents.handle_agent_staging() for 6GUPWF25 : Invalid ciphertext received.
[*] Agent 6GUPWF25 deleted
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/share/powershell-empire/lib/common/helpers.py", line 1026, in __run
    self.__run_backup()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/share/powershell-empire//lib/listeners/dbx.py", line 959, in start_server
    dataResults = self.mainMenu.agents.handle_agent_data(stagingKey, stageData, listenerOptions)
  File "/usr/share/powershell-empire/lib/common/agents.py", line 1606, in handle_agent_data
    dataToReturn.append((language, self.handle_agent_staging(sessionID, language, meta, additional, encData, stagingKey, listenerOptions, clientIP)))
  File "/usr/share/powershell-empire/lib/common/agents.py", line 1451, in handle_agent_staging
    sessionKey = (self.agents[sessionID]['sessionKey'])
KeyError: 'TYV2NGZ6'
```

**Comment by Cx01N** [comment]
Did you try running `sudo ./empire --reset` and starting the listener from a fresh instance? I just want to make sure we rule everything out first.

**Comment by WhatIsRealityBro** [comment]
That's a handy command! To make sure nothing else is interfering I reinstalled all of Powershell Empire as well as ran the command you provided. This time I got a little further and got a slightly different error:
```

(Empire: listeners/dbx) > [*] New agent 46EP7LZ2 checked in
[*] Uploading key negotiation part 2 to /Empire/staging/46EP7LZ2_2.txt for 46EP7LZ2
[+] Initial agent 46EP7LZ2 from 0.0.0.0 now active (Slack)
[*] Sending agent (stage 2) to 46EP7LZ2 through Dropbox
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/share/powershell-empire/lib/common/helpers.py", line 1026, in __run
    self.__run_backup()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/share/powershell-empire//lib/listeners/dbx.py", line 997, in start_server
    agentCode = self.generate_agent(language=language, listenerOptions=listenerOptions)
  File "/usr/share/powershell-empire//lib/listeners/dbx.py", line 458, in generate_agent
    b64DefaultResponse = base64.b64encode(self.default_response())
  File "/usr/lib/python3.8/base64.py", line 58, in b64encode
    encoded = binascii.b2a_base64(s, newline=False)
TypeError: a bytes-like object is required, not 'str'
```

**Comment by WhatIsRealityBro** [comment]
I tried adding the .encode('UTF-8') to the lines it's having trouble with but I still can't seem to get past that error - I might be doing it wrong though. I apologize if this is something trivial that's just going over my head!

**Comment by Cx01N** [comment]
@WhatIsRealityBro good catch, not sure how I missed that. But, I updated the branch for #327 to include the fix. Cross our fingers that it works this time!

**Comment by WhatIsRealityBro** [comment]
@Cx01N Works great! Thanks for all your help with this!
