### ISSUE TITLE
Error: Error: Request failed with status code 500[BUG]

### ISSUE THREAD

**Issue by SeeNanshaneisurely** [BC-SECURITY/Empire#669]
__Note:__ Please fill out all sections (if applicable) and do not delete the below section headers, otherwise the bot will close the issue.

## Empire Version
- Empire 5.2.2

## OS Information (Linux flavor, Python version)
- OS: Ubuntu 20
- Python: python3.8

## Describe the bug
Create "multi_pyinstaller" error

## To Reproduce
1. Click Submit
2. See error
<img width="847" alt="微信图片_20230524172012" src="https://github.com/BC-SECURITY/Empire/assets/57738442/c0713b81-d413-41cd-a953-9eb300873cb3">

**Comment by SeeNanshaneisurely** [comment]
Hello!
Is there an update

**Comment by Cx01N** [comment]
We put a fix into 5.5 that should fix this problem.
https://github.com/BC-SECURITY/Empire-Sponsors/pull/642

**Comment by SeeNanshaneisurely** [comment]
Hello!
5.5 When will it be released
![image](https://github.com/BC-SECURITY/Empire/assets/57738442/2456f57f-4e59-414a-85eb-1afc14b6a1d3)

**Comment by Cx01N** [comment]
There are 30 days where sponsors get early access and then it will go public for everyone.

**Comment by Cx01N** [comment]
Closing since 5.5 is public, let me know if the issue persists and we can reopen the issue.

**Comment by SeeNanshaneisurely** [comment]
Hello!
After testing the latest version 5.6, it was found that the previous problems still exist.
environment:kali
![image](https://github.com/BC-SECURITY/Empire/assets/57738442/29c8177f-3558-47b1-bea4-8c1737f89752)

**Comment by SeeNanshaneisurely** [comment]
Will subsequent versions add new Linux shells?
Generate binary file

**Comment by SeeNanshaneisurely** [comment]
Complete error report
![image](https://github.com/BC-SECURITY/Empire/assets/57738442/24353d46-1007-4db4-a873-61db2b9071b2)

**Comment by SeeNanshaneisurely** [comment]
solved
